# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='svgtrace',
    version='2020.0.3',
    description='Leverage pyppeteer and the imagetrace.js library to trace a bitmap to svg in python',
    python_requires='==3.*,>=3.6.1',
    project_urls={
        "documentation":
            "https://github.com/FHPythonUtils/SvgTrace/blob/master/README.md",
        "homepage":
            "https://github.com/FHPythonUtils/SvgTrace",
        "repository":
            "https://github.com/FHPythonUtils/SvgTrace"
    },
    author='FredHappyface',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers', 'Intended Audience :: Education',
        'License :: OSI Approved :: MIT License', 'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: Implementation :: CPython',
        'Topic :: Multimedia :: Graphics',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Utilities'
    ],
    packages=['SvgTrace'],
    package_dir={"": "."},
    package_data={"svgtrace": ["*.html", "*.js"]},
    install_requires=['metprint==2020.*,>=2020.6.0', 'pyppeteer==0.*,>=0.2.2'],
)
