# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='svgtrace',
    version='2020',
    description='Leverage pyppeteer and the imagetrace.js library to trace a bitmap to svg in python',
    python_requires='==3.*,>=3.5.0',
    project_urls={
        "documentation":
            "https://github.com/FHPythonUtils/MetPrint/blob/master/README.md",
        "homepage":
            "https://github.com/FHPythonUtils/MetPrint",
        "repository":
            "https://github.com/FHPythonUtils/MetPrint"
    },
    author='FredHappyface',
    classifiers=[
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Operating System :: OS Independent'
    ],
    packages=['SvgTrace'],
    package_dir={"": "."},
    package_data={"svgtrace": ["*.html", "*.js"]},
    install_requires=['metprint==2020.*,>=2020.6.0',
                      'pyppeteer==0.*,>=0.0.25'],
)
